<a href="https://colab.research.google.com/github/RomaniMateus/Pytorch-course-I/blob/main/lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# 1. Working with different types of tensors

In [2]:
float_list = [[1, 2, 3], [4, 5, 6]]
tns = torch.FloatTensor(float_list)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
int_list = [[1, 2, 3], [4, 5, 6]]
tns = torch.LongTensor(int_list)
print(tns.dtype)
print(tns)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


## Other ways to initialize tensors

### From numpy array

In [4]:
numpy_list = np.random.randn(2, 3)
numpy_tensor = torch.from_numpy(numpy_list)

print(numpy_list)
print(numpy_tensor)

[[-0.42105167  0.904173   -1.09933162]
 [ 1.79458507 -1.45728585  1.37098994]]
tensor([[-0.4211,  0.9042, -1.0993],
        [ 1.7946, -1.4573,  1.3710]], dtype=torch.float64)


### From default tensors (ones, zeros and random)

`torch.ones()` -> Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument `size`.

`torch.zeros()` -> Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument `size`.

`torch.randn()` -> Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1, with the shape defined by the variable argument `size`.

In [5]:
ones_tensor = torch.ones((2, 3))
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
zeros_tensor = torch.zeros((2, 3))
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
randn_tensor = torch.randn((2, 3))
print(randn_tensor)

tensor([[ 0.8466, -0.1844, -0.5630],
        [-1.0801, -0.0112,  0.6815]])


### From tensors to numpy arrays

In [8]:
numpy_from_tensor = randn_tensor.data.numpy()
print(numpy_from_tensor)

[[ 0.84662384 -0.18443875 -0.5630274 ]
 [-1.080127   -0.01115962  0.6815074 ]]


# 2. Slicing operations on tensors

The syntax for slicing operations on tensors is similar to that of numpy arrays, using the square brackets and the colon `:` symbol.

In [9]:
tnsr = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(tnsr)

tnsr_slice = tnsr[:, 1:]
print("Slice example:\n", tnsr_slice)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Slice example:
 tensor([[2., 3.],
        [5., 6.]])


In [10]:
tnsr[:2, 0] = 0
print(tnsr)

tensor([[0., 2., 3.],
        [0., 5., 6.]])


# 3. Functions .size() and .view()

The function `.size()` returns the shape of a tensor. The function `.view()` returns a new tensor with the same data as the original tensor but with a different shape.

In [11]:
print(tnsr)

tensor([[0., 2., 3.],
        [0., 5., 6.]])


In [12]:
print(tnsr.size())

torch.Size([2, 3])


In [13]:
one_dimensional_tnsr = tnsr.view(-1)
two_dimensional_tnsr = tnsr.view(3, 2)
one_column_tnsr = tnsr.view(6, 1)

print(one_dimensional_tnsr)
print(two_dimensional_tnsr)
print(one_column_tnsr)

tensor([0., 2., 3., 0., 5., 6.])
tensor([[0., 2.],
        [3., 0.],
        [5., 6.]])
tensor([[0.],
        [2.],
        [3.],
        [0.],
        [5.],
        [6.]])


In [14]:
print(one_dimensional_tnsr.size())
print(two_dimensional_tnsr.size())
print(one_column_tnsr.size())



torch.Size([6])
torch.Size([3, 2])
torch.Size([6, 1])


# 4. GPU Casting

In order to cast a tensor to GPU, we need to use the `.cuda()` function. In order to cast a tensor to CPU, we need to use the `.cpu()` function.

In [16]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(device)



cuda
