In [35]:
import torch
import numpy as np

# 1. Working with different types of tensors

In [36]:
float_list = [[1, 2, 3], [4, 5, 6]]
tns = torch.FloatTensor(float_list)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [37]:
int_list = [[1, 2, 3], [4, 5, 6]]
tns = torch.LongTensor(int_list)
print(tns.dtype)
print(tns)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


## Other ways to initialize tensors

### From numpy array

In [38]:
numpy_list = np.random.randn(2, 3)
numpy_tensor = torch.from_numpy(numpy_list)

print(numpy_list)
print(numpy_tensor)

[[-1.26378624 -0.45746096 -1.16605891]
 [-0.40208659 -1.19138426 -0.08647182]]
tensor([[-1.2638, -0.4575, -1.1661],
        [-0.4021, -1.1914, -0.0865]], dtype=torch.float64)


### From default tensors (ones, zeros and random)

`torch.ones()` -> Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument `size`.

`torch.zeros()` -> Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument `size`.

`torch.randn()` -> Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1, with the shape defined by the variable argument `size`.

In [39]:
ones_tensor = torch.ones((2, 3))
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [40]:
zeros_tensor = torch.zeros((2, 3))
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [41]:
randn_tensor = torch.randn((2, 3))
print(randn_tensor)

tensor([[-0.1359, -0.3300, -1.3509],
        [ 1.5725,  0.7202, -0.9631]])


### From tensors to numpy arrays

In [42]:
numpy_from_tensor = randn_tensor.data.numpy()
print(numpy_from_tensor)

[[-0.13590503 -0.3300194  -1.350853  ]
 [ 1.5724803   0.72019446 -0.963121  ]]


# 2. Slicing operations on tensors

The syntax for slicing operations on tensors is similar to that of numpy arrays, using the square brackets and the colon `:` symbol.

In [43]:
tnsr = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(tnsr)

tnsr_slice = tnsr[:, 1:]
print("Slice example:\n", tnsr_slice)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Slice example:
 tensor([[2., 3.],
        [5., 6.]])


In [ ]:
tnsr[:2, 0] = 0
print(tnsr)

# 3. Functions .size() and .view()

The function `.size()` returns the shape of a tensor. The function `.view()` returns a new tensor with the same data as the original tensor but with a different shape.

In [46]:
print(tnsr)

tensor([[0., 2., 3.],
        [0., 5., 6.]])


In [45]:
print(tnsr.size())

torch.Size([2, 3])


In [51]:
one_dimensional_tnsr = tnsr.view(-1)
two_dimensional_tnsr = tnsr.view(3, 2)
one_column_tnsr = tnsr.view(6, 1)

print(one_dimensional_tnsr)
print(two_dimensional_tnsr)
print(one_column_tnsr)

tensor([0., 2., 3., 0., 5., 6.])
tensor([[0., 2.],
        [3., 0.],
        [5., 6.]])
tensor([[0.],
        [2.],
        [3.],
        [0.],
        [5.],
        [6.]])


In [ ]:
print(one_dimensional_tnsr.size())
print(two_dimensional_tnsr.size())
print(one_column_tnsr.size())

# 4. GPU Casting

In order to cast a tensor to GPU, we need to use the `.cuda()` function. In order to cast a tensor to CPU, we need to use the `.cpu()` function.

In [54]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
    
print(device)

False